- name: ec2 launcher
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/packt
  tasks:
    - name: launching first ec2
      ec2:
        instance_type: "{{ aws_instance_type }}"
        key_name: "{{ aws_key_name }}"
        image: "{{ aws_image }}"
        region: "{{ aws_region }}"
        group_id: sg-2fa1114f
        count: 1
        vpc_subnet_id: "{{ aws_subnet_id }}"
        wait: yes
        assign_public_ip: yes
   

